# Generated by Django 6.0.4 on 2026-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.ImageField(upload_to='slider/')),
                ('image_width', models.PositiveIntegerField(default=285)),
                ('image_height', models.PositiveIntegerField(default=437)),
                ('anchor_url', models.URLField(blank=True)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
    ]
