# Generated by Django 6.0.4 on 2026-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='movie_genre',
        ),
        migrations.AddField(
            model_name='slider',
            name='movie_genre',
            field=models.ManyToManyField(to='movApp.genre'),
        ),
    ]
