# Generated by Django 6.0.4 on 2026-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movApp', '0002_genre_remove_slider_movie_genre_slider_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='movie_genre',
            new_name='genres',
        ),
        migrations.AddField(
            model_name='genre',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
