# Generated by Django 6.0.4 on 2026-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movApp', '0004_advertisment_sociallink_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.ImageField(upload_to='trailers/')),
                ('img_alt', models.CharField(max_length=100)),
                ('img_width', models.PositiveIntegerField(default=255)),
                ('img_height', models.PositiveIntegerField(default=170)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
    ]
