# Generated by Django 6.0.4 on 2026-04-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movApp', '0005_traileritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='traileritem',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movApp.trailer'),
        ),
    ]
