# Generated by Django 6.0.4 on 2026-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movApp', '0008_alter_advertisment_id_alter_celebrity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
