# Generated by Django 5.2.7 on 2026-04-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movApp', '0009_alter_advertisment_id_alter_celebrity_id_and_more'),
        ('movApp', '0009_newslettersubscriber_alter_advertisment_id_and_more'),
    ]

    operations = [
    ]
