# Generated by Django 5.2.7 on 2026-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movApp', '0011_alter_advertisment_id_alter_celebrity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_src',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
